-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_sobel_axi_stream_top is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    p_src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    p_src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    p_src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_src_TVALID : IN STD_LOGIC;
    p_src_TREADY : OUT STD_LOGIC;
    p_dst_TVALID : OUT STD_LOGIC;
    p_dst_TREADY : IN STD_LOGIC );
end;


architecture behav of hls_sobel_axi_stream_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_sobel_axi_stream_top_hls_sobel_axi_stream_top,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.180500,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=3259,HLS_SYN_LUT=4166,HLS_VERSION=2020_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_write : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_din : STD_LOGIC_VECTOR (23 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_p_src_TREADY : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_img_buf_0_472_read : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_din : STD_LOGIC_VECTOR (7 downto 0);
    signal bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_write : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_p_src_1_read : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_p_src_2_read : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_ap_start : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_ap_done : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_ap_continue : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_ap_idle : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_ap_ready : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1_473_read : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_write : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_write : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_1_read : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_2_read : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_img_buf_1a_474_read : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_img_buf_1b_475_read : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_din : STD_LOGIC_VECTOR (7 downto 0);
    signal addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_write : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_src1_1_read : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_src1_2_read : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_img_buf_2_476_read : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_din : STD_LOGIC_VECTOR (23 downto 0);
    signal gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_write : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_p_src_1_read : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_p_src_2_read : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_img_buf_3_477_read : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TVALID : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal img_buf_0_rows_c_full_n : STD_LOGIC;
    signal img_buf_0_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_0_rows_c_empty_n : STD_LOGIC;
    signal img_buf_0_cols_c_full_n : STD_LOGIC;
    signal img_buf_0_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_0_cols_c_empty_n : STD_LOGIC;
    signal img_buf_1_rows_c_full_n : STD_LOGIC;
    signal img_buf_1_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_1_rows_c_empty_n : STD_LOGIC;
    signal img_buf_1_cols_c_full_n : STD_LOGIC;
    signal img_buf_1_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_1_cols_c_empty_n : STD_LOGIC;
    signal img_buf_1a_rows_c_full_n : STD_LOGIC;
    signal img_buf_1a_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_1a_rows_c_empty_n : STD_LOGIC;
    signal img_buf_1a_cols_c_full_n : STD_LOGIC;
    signal img_buf_1a_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_1a_cols_c_empty_n : STD_LOGIC;
    signal img_buf_2_rows_c_full_n : STD_LOGIC;
    signal img_buf_2_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_2_rows_c_empty_n : STD_LOGIC;
    signal img_buf_2_cols_c_full_n : STD_LOGIC;
    signal img_buf_2_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_2_cols_c_empty_n : STD_LOGIC;
    signal img_buf_3_rows_c_full_n : STD_LOGIC;
    signal img_buf_3_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_3_rows_c_empty_n : STD_LOGIC;
    signal img_buf_3_cols_c_full_n : STD_LOGIC;
    signal img_buf_3_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_3_cols_c_empty_n : STD_LOGIC;
    signal img_buf_0_data_full_n : STD_LOGIC;
    signal img_buf_0_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal img_buf_0_data_empty_n : STD_LOGIC;
    signal img_buf_0_rows_c15_full_n : STD_LOGIC;
    signal img_buf_0_rows_c15_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_0_rows_c15_empty_n : STD_LOGIC;
    signal img_buf_0_cols_c16_full_n : STD_LOGIC;
    signal img_buf_0_cols_c16_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_buf_0_cols_c16_empty_n : STD_LOGIC;
    signal img_buf_1_data_full_n : STD_LOGIC;
    signal img_buf_1_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_buf_1_data_empty_n : STD_LOGIC;
    signal img_buf_1a_data_full_n : STD_LOGIC;
    signal img_buf_1a_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_buf_1a_data_empty_n : STD_LOGIC;
    signal img_buf_1b_data_full_n : STD_LOGIC;
    signal img_buf_1b_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_buf_1b_data_empty_n : STD_LOGIC;
    signal img_buf_2_data_full_n : STD_LOGIC;
    signal img_buf_2_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_buf_2_data_empty_n : STD_LOGIC;
    signal img_buf_3_data_full_n : STD_LOGIC;
    signal img_buf_3_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal img_buf_3_data_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready : STD_LOGIC;
    signal Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_full_n : STD_LOGIC;
    signal start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_empty_n : STD_LOGIC;
    signal start_for_addWeighted_0_0_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_addWeighted_0_0_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_addWeighted_0_0_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_addWeighted_0_0_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal start_for_gray2bgr_0_9_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gray2bgr_0_9_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_gray2bgr_0_9_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gray2bgr_0_9_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal start_for_bgr2gray_9_0_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_bgr2gray_9_0_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_bgr2gray_9_0_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_bgr2gray_9_0_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal bgr2gray_9_0_1080_1920_1_U0_start_write : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_start_full_n : STD_LOGIC;
    signal Sobel_0_3_0_0_1080_1920_1_false_U0_start_write : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal addWeighted_0_0_1080_1920_1_U0_start_write : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal gray2bgr_0_9_1080_1920_1_U0_start_write : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write : STD_LOGIC;

    component hls_sobel_axi_stream_top_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        img_buf_0_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_0_rows_out_full_n : IN STD_LOGIC;
        img_buf_0_rows_out_write : OUT STD_LOGIC;
        img_buf_0_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_0_cols_out_full_n : IN STD_LOGIC;
        img_buf_0_cols_out_write : OUT STD_LOGIC;
        img_buf_1_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_1_rows_out_full_n : IN STD_LOGIC;
        img_buf_1_rows_out_write : OUT STD_LOGIC;
        img_buf_1_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_1_cols_out_full_n : IN STD_LOGIC;
        img_buf_1_cols_out_write : OUT STD_LOGIC;
        img_buf_1a_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_1a_rows_out_full_n : IN STD_LOGIC;
        img_buf_1a_rows_out_write : OUT STD_LOGIC;
        img_buf_1a_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_1a_cols_out_full_n : IN STD_LOGIC;
        img_buf_1a_cols_out_write : OUT STD_LOGIC;
        img_buf_2_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_2_rows_out_full_n : IN STD_LOGIC;
        img_buf_2_rows_out_write : OUT STD_LOGIC;
        img_buf_2_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_2_cols_out_full_n : IN STD_LOGIC;
        img_buf_2_cols_out_write : OUT STD_LOGIC;
        img_buf_3_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_3_rows_out_full_n : IN STD_LOGIC;
        img_buf_3_rows_out_write : OUT STD_LOGIC;
        img_buf_3_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_buf_3_cols_out_full_n : IN STD_LOGIC;
        img_buf_3_cols_out_write : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_AXIvideo2xfMat_24_9_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_buf_0_472_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        img_buf_0_472_full_n : IN STD_LOGIC;
        img_buf_0_472_write : OUT STD_LOGIC;
        p_src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        p_src_TVALID : IN STD_LOGIC;
        p_src_TREADY : OUT STD_LOGIC;
        p_src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        p_src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        p_src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        p_src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_1_empty_n : IN STD_LOGIC;
        img_1_read : OUT STD_LOGIC;
        img_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_2_empty_n : IN STD_LOGIC;
        img_2_read : OUT STD_LOGIC;
        img_1_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_1_out_full_n : IN STD_LOGIC;
        img_1_out_write : OUT STD_LOGIC;
        img_2_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_2_out_full_n : IN STD_LOGIC;
        img_2_out_write : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_bgr2gray_9_0_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_0_472_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_buf_0_472_empty_n : IN STD_LOGIC;
        img_buf_0_472_read : OUT STD_LOGIC;
        img_buf_1_473_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1_473_full_n : IN STD_LOGIC;
        img_buf_1_473_write : OUT STD_LOGIC;
        p_src_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_1_empty_n : IN STD_LOGIC;
        p_src_1_read : OUT STD_LOGIC;
        p_src_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_2_empty_n : IN STD_LOGIC;
        p_src_2_read : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_Sobel_0_3_0_0_1080_1920_1_false_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_1_473_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1_473_empty_n : IN STD_LOGIC;
        img_buf_1_473_read : OUT STD_LOGIC;
        img_buf_1a_474_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1a_474_full_n : IN STD_LOGIC;
        img_buf_1a_474_write : OUT STD_LOGIC;
        img_buf_1b_475_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1b_475_full_n : IN STD_LOGIC;
        img_buf_1b_475_write : OUT STD_LOGIC;
        p_src_mat_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_mat_1_empty_n : IN STD_LOGIC;
        p_src_mat_1_read : OUT STD_LOGIC;
        p_src_mat_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_mat_2_empty_n : IN STD_LOGIC;
        p_src_mat_2_read : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_addWeighted_0_0_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_1a_474_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1a_474_empty_n : IN STD_LOGIC;
        img_buf_1a_474_read : OUT STD_LOGIC;
        img_buf_1b_475_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_buf_1b_475_empty_n : IN STD_LOGIC;
        img_buf_1b_475_read : OUT STD_LOGIC;
        img_buf_2_476_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_buf_2_476_full_n : IN STD_LOGIC;
        img_buf_2_476_write : OUT STD_LOGIC;
        src1_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src1_1_empty_n : IN STD_LOGIC;
        src1_1_read : OUT STD_LOGIC;
        src1_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src1_2_empty_n : IN STD_LOGIC;
        src1_2_read : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_gray2bgr_0_9_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_2_476_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_buf_2_476_empty_n : IN STD_LOGIC;
        img_buf_2_476_read : OUT STD_LOGIC;
        img_buf_3_477_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        img_buf_3_477_full_n : IN STD_LOGIC;
        img_buf_3_477_write : OUT STD_LOGIC;
        p_src_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_1_empty_n : IN STD_LOGIC;
        p_src_1_read : OUT STD_LOGIC;
        p_src_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_2_empty_n : IN STD_LOGIC;
        p_src_2_read : OUT STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_xfMat2AXIvideo_24_9_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_buf_3_477_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_buf_3_477_empty_n : IN STD_LOGIC;
        img_buf_3_477_read : OUT STD_LOGIC;
        img_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_1_empty_n : IN STD_LOGIC;
        img_1_read : OUT STD_LOGIC;
        img_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_2_empty_n : IN STD_LOGIC;
        img_2_read : OUT STD_LOGIC;
        p_dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_dst_TVALID : OUT STD_LOGIC;
        p_dst_TREADY : IN STD_LOGIC;
        p_dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        p_dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        p_dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component hls_sobel_axi_stream_top_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w32_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w32_d5_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w32_d6_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w32_d7_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w24_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_start_for_Sobel_0_3_0_0_1080_1920_1_false_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_start_for_addWeighted_0_0_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_start_for_gray2bgr_0_9_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_start_for_bgr2gray_9_0_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_sobel_axi_stream_top_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component hls_sobel_axi_stream_top_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rows => rows,
        cols => cols,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0 : component hls_sobel_axi_stream_top_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start,
        start_full_n => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n,
        ap_done => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done,
        ap_continue => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue,
        ap_idle => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle,
        ap_ready => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready,
        start_out => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out,
        start_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write,
        rows => rows,
        cols => cols,
        img_buf_0_rows_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_din,
        img_buf_0_rows_out_full_n => img_buf_0_rows_c_full_n,
        img_buf_0_rows_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_write,
        img_buf_0_cols_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_din,
        img_buf_0_cols_out_full_n => img_buf_0_cols_c_full_n,
        img_buf_0_cols_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_write,
        img_buf_1_rows_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_din,
        img_buf_1_rows_out_full_n => img_buf_1_rows_c_full_n,
        img_buf_1_rows_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_write,
        img_buf_1_cols_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_din,
        img_buf_1_cols_out_full_n => img_buf_1_cols_c_full_n,
        img_buf_1_cols_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_write,
        img_buf_1a_rows_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_din,
        img_buf_1a_rows_out_full_n => img_buf_1a_rows_c_full_n,
        img_buf_1a_rows_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_write,
        img_buf_1a_cols_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_din,
        img_buf_1a_cols_out_full_n => img_buf_1a_cols_c_full_n,
        img_buf_1a_cols_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_write,
        img_buf_2_rows_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_din,
        img_buf_2_rows_out_full_n => img_buf_2_rows_c_full_n,
        img_buf_2_rows_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_write,
        img_buf_2_cols_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_din,
        img_buf_2_cols_out_full_n => img_buf_2_cols_c_full_n,
        img_buf_2_cols_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_write,
        img_buf_3_rows_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_din,
        img_buf_3_rows_out_full_n => img_buf_3_rows_c_full_n,
        img_buf_3_rows_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_write,
        img_buf_3_cols_out_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_din,
        img_buf_3_cols_out_full_n => img_buf_3_cols_c_full_n,
        img_buf_3_cols_out_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_write);

    AXIvideo2xfMat_24_9_1080_1920_1_U0 : component hls_sobel_axi_stream_top_AXIvideo2xfMat_24_9_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start,
        start_full_n => start_for_bgr2gray_9_0_1080_1920_1_U0_full_n,
        ap_done => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done,
        ap_continue => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue,
        ap_idle => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle,
        ap_ready => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready,
        start_out => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out,
        start_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write,
        img_buf_0_472_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_din,
        img_buf_0_472_full_n => img_buf_0_data_full_n,
        img_buf_0_472_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_write,
        p_src_TDATA => p_src_TDATA,
        p_src_TVALID => p_src_TVALID,
        p_src_TREADY => AXIvideo2xfMat_24_9_1080_1920_1_U0_p_src_TREADY,
        p_src_TKEEP => p_src_TKEEP,
        p_src_TSTRB => p_src_TSTRB,
        p_src_TUSER => p_src_TUSER,
        p_src_TLAST => p_src_TLAST,
        p_src_TID => p_src_TID,
        p_src_TDEST => p_src_TDEST,
        img_1_dout => img_buf_0_rows_c_dout,
        img_1_empty_n => img_buf_0_rows_c_empty_n,
        img_1_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read,
        img_2_dout => img_buf_0_cols_c_dout,
        img_2_empty_n => img_buf_0_cols_c_empty_n,
        img_2_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read,
        img_1_out_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din,
        img_1_out_full_n => img_buf_0_rows_c15_full_n,
        img_1_out_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write,
        img_2_out_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din,
        img_2_out_full_n => img_buf_0_cols_c16_full_n,
        img_2_out_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write);

    bgr2gray_9_0_1080_1920_1_U0 : component hls_sobel_axi_stream_top_bgr2gray_9_0_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => bgr2gray_9_0_1080_1920_1_U0_ap_start,
        ap_done => bgr2gray_9_0_1080_1920_1_U0_ap_done,
        ap_continue => bgr2gray_9_0_1080_1920_1_U0_ap_continue,
        ap_idle => bgr2gray_9_0_1080_1920_1_U0_ap_idle,
        ap_ready => bgr2gray_9_0_1080_1920_1_U0_ap_ready,
        img_buf_0_472_dout => img_buf_0_data_dout,
        img_buf_0_472_empty_n => img_buf_0_data_empty_n,
        img_buf_0_472_read => bgr2gray_9_0_1080_1920_1_U0_img_buf_0_472_read,
        img_buf_1_473_din => bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_din,
        img_buf_1_473_full_n => img_buf_1_data_full_n,
        img_buf_1_473_write => bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_write,
        p_src_1_dout => img_buf_0_rows_c15_dout,
        p_src_1_empty_n => img_buf_0_rows_c15_empty_n,
        p_src_1_read => bgr2gray_9_0_1080_1920_1_U0_p_src_1_read,
        p_src_2_dout => img_buf_0_cols_c16_dout,
        p_src_2_empty_n => img_buf_0_cols_c16_empty_n,
        p_src_2_read => bgr2gray_9_0_1080_1920_1_U0_p_src_2_read);

    Sobel_0_3_0_0_1080_1920_1_false_U0 : component hls_sobel_axi_stream_top_Sobel_0_3_0_0_1080_1920_1_false_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_start,
        ap_done => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_done,
        ap_continue => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_continue,
        ap_idle => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_idle,
        ap_ready => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_ready,
        img_buf_1_473_dout => img_buf_1_data_dout,
        img_buf_1_473_empty_n => img_buf_1_data_empty_n,
        img_buf_1_473_read => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1_473_read,
        img_buf_1a_474_din => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_din,
        img_buf_1a_474_full_n => img_buf_1a_data_full_n,
        img_buf_1a_474_write => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_write,
        img_buf_1b_475_din => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_din,
        img_buf_1b_475_full_n => img_buf_1b_data_full_n,
        img_buf_1b_475_write => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_write,
        p_src_mat_1_dout => img_buf_1_rows_c_dout,
        p_src_mat_1_empty_n => img_buf_1_rows_c_empty_n,
        p_src_mat_1_read => Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_1_read,
        p_src_mat_2_dout => img_buf_1_cols_c_dout,
        p_src_mat_2_empty_n => img_buf_1_cols_c_empty_n,
        p_src_mat_2_read => Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_2_read);

    addWeighted_0_0_1080_1920_1_U0 : component hls_sobel_axi_stream_top_addWeighted_0_0_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => addWeighted_0_0_1080_1920_1_U0_ap_start,
        ap_done => addWeighted_0_0_1080_1920_1_U0_ap_done,
        ap_continue => addWeighted_0_0_1080_1920_1_U0_ap_continue,
        ap_idle => addWeighted_0_0_1080_1920_1_U0_ap_idle,
        ap_ready => addWeighted_0_0_1080_1920_1_U0_ap_ready,
        img_buf_1a_474_dout => img_buf_1a_data_dout,
        img_buf_1a_474_empty_n => img_buf_1a_data_empty_n,
        img_buf_1a_474_read => addWeighted_0_0_1080_1920_1_U0_img_buf_1a_474_read,
        img_buf_1b_475_dout => img_buf_1b_data_dout,
        img_buf_1b_475_empty_n => img_buf_1b_data_empty_n,
        img_buf_1b_475_read => addWeighted_0_0_1080_1920_1_U0_img_buf_1b_475_read,
        img_buf_2_476_din => addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_din,
        img_buf_2_476_full_n => img_buf_2_data_full_n,
        img_buf_2_476_write => addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_write,
        src1_1_dout => img_buf_1a_rows_c_dout,
        src1_1_empty_n => img_buf_1a_rows_c_empty_n,
        src1_1_read => addWeighted_0_0_1080_1920_1_U0_src1_1_read,
        src1_2_dout => img_buf_1a_cols_c_dout,
        src1_2_empty_n => img_buf_1a_cols_c_empty_n,
        src1_2_read => addWeighted_0_0_1080_1920_1_U0_src1_2_read);

    gray2bgr_0_9_1080_1920_1_U0 : component hls_sobel_axi_stream_top_gray2bgr_0_9_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => gray2bgr_0_9_1080_1920_1_U0_ap_start,
        ap_done => gray2bgr_0_9_1080_1920_1_U0_ap_done,
        ap_continue => gray2bgr_0_9_1080_1920_1_U0_ap_continue,
        ap_idle => gray2bgr_0_9_1080_1920_1_U0_ap_idle,
        ap_ready => gray2bgr_0_9_1080_1920_1_U0_ap_ready,
        img_buf_2_476_dout => img_buf_2_data_dout,
        img_buf_2_476_empty_n => img_buf_2_data_empty_n,
        img_buf_2_476_read => gray2bgr_0_9_1080_1920_1_U0_img_buf_2_476_read,
        img_buf_3_477_din => gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_din,
        img_buf_3_477_full_n => img_buf_3_data_full_n,
        img_buf_3_477_write => gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_write,
        p_src_1_dout => img_buf_2_rows_c_dout,
        p_src_1_empty_n => img_buf_2_rows_c_empty_n,
        p_src_1_read => gray2bgr_0_9_1080_1920_1_U0_p_src_1_read,
        p_src_2_dout => img_buf_2_cols_c_dout,
        p_src_2_empty_n => img_buf_2_cols_c_empty_n,
        p_src_2_read => gray2bgr_0_9_1080_1920_1_U0_p_src_2_read);

    xfMat2AXIvideo_24_9_1080_1920_1_U0 : component hls_sobel_axi_stream_top_xfMat2AXIvideo_24_9_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start,
        ap_done => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done,
        ap_continue => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue,
        ap_idle => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle,
        ap_ready => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready,
        img_buf_3_477_dout => img_buf_3_data_dout,
        img_buf_3_477_empty_n => img_buf_3_data_empty_n,
        img_buf_3_477_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_buf_3_477_read,
        img_1_dout => img_buf_3_rows_c_dout,
        img_1_empty_n => img_buf_3_rows_c_empty_n,
        img_1_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read,
        img_2_dout => img_buf_3_cols_c_dout,
        img_2_empty_n => img_buf_3_cols_c_empty_n,
        img_2_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read,
        p_dst_TDATA => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDATA,
        p_dst_TVALID => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TVALID,
        p_dst_TREADY => p_dst_TREADY,
        p_dst_TKEEP => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TKEEP,
        p_dst_TSTRB => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TSTRB,
        p_dst_TUSER => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TUSER,
        p_dst_TLAST => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TLAST,
        p_dst_TID => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TID,
        p_dst_TDEST => xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDEST);

    img_buf_0_rows_c_U : component hls_sobel_axi_stream_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_din,
        if_full_n => img_buf_0_rows_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_rows_out_write,
        if_dout => img_buf_0_rows_c_dout,
        if_empty_n => img_buf_0_rows_c_empty_n,
        if_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read);

    img_buf_0_cols_c_U : component hls_sobel_axi_stream_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_din,
        if_full_n => img_buf_0_cols_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_0_cols_out_write,
        if_dout => img_buf_0_cols_c_dout,
        if_empty_n => img_buf_0_cols_c_empty_n,
        if_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read);

    img_buf_1_rows_c_U : component hls_sobel_axi_stream_top_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_din,
        if_full_n => img_buf_1_rows_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_rows_out_write,
        if_dout => img_buf_1_rows_c_dout,
        if_empty_n => img_buf_1_rows_c_empty_n,
        if_read => Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_1_read);

    img_buf_1_cols_c_U : component hls_sobel_axi_stream_top_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_din,
        if_full_n => img_buf_1_cols_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1_cols_out_write,
        if_dout => img_buf_1_cols_c_dout,
        if_empty_n => img_buf_1_cols_c_empty_n,
        if_read => Sobel_0_3_0_0_1080_1920_1_false_U0_p_src_mat_2_read);

    img_buf_1a_rows_c_U : component hls_sobel_axi_stream_top_fifo_w32_d5_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_din,
        if_full_n => img_buf_1a_rows_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_rows_out_write,
        if_dout => img_buf_1a_rows_c_dout,
        if_empty_n => img_buf_1a_rows_c_empty_n,
        if_read => addWeighted_0_0_1080_1920_1_U0_src1_1_read);

    img_buf_1a_cols_c_U : component hls_sobel_axi_stream_top_fifo_w32_d5_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_din,
        if_full_n => img_buf_1a_cols_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_1a_cols_out_write,
        if_dout => img_buf_1a_cols_c_dout,
        if_empty_n => img_buf_1a_cols_c_empty_n,
        if_read => addWeighted_0_0_1080_1920_1_U0_src1_2_read);

    img_buf_2_rows_c_U : component hls_sobel_axi_stream_top_fifo_w32_d6_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_din,
        if_full_n => img_buf_2_rows_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_rows_out_write,
        if_dout => img_buf_2_rows_c_dout,
        if_empty_n => img_buf_2_rows_c_empty_n,
        if_read => gray2bgr_0_9_1080_1920_1_U0_p_src_1_read);

    img_buf_2_cols_c_U : component hls_sobel_axi_stream_top_fifo_w32_d6_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_din,
        if_full_n => img_buf_2_cols_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_2_cols_out_write,
        if_dout => img_buf_2_cols_c_dout,
        if_empty_n => img_buf_2_cols_c_empty_n,
        if_read => gray2bgr_0_9_1080_1920_1_U0_p_src_2_read);

    img_buf_3_rows_c_U : component hls_sobel_axi_stream_top_fifo_w32_d7_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_din,
        if_full_n => img_buf_3_rows_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_rows_out_write,
        if_dout => img_buf_3_rows_c_dout,
        if_empty_n => img_buf_3_rows_c_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read);

    img_buf_3_cols_c_U : component hls_sobel_axi_stream_top_fifo_w32_d7_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_din,
        if_full_n => img_buf_3_cols_c_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_buf_3_cols_out_write,
        if_dout => img_buf_3_cols_c_dout,
        if_empty_n => img_buf_3_cols_c_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read);

    img_buf_0_data_U : component hls_sobel_axi_stream_top_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_din,
        if_full_n => img_buf_0_data_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_buf_0_472_write,
        if_dout => img_buf_0_data_dout,
        if_empty_n => img_buf_0_data_empty_n,
        if_read => bgr2gray_9_0_1080_1920_1_U0_img_buf_0_472_read);

    img_buf_0_rows_c15_U : component hls_sobel_axi_stream_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din,
        if_full_n => img_buf_0_rows_c15_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write,
        if_dout => img_buf_0_rows_c15_dout,
        if_empty_n => img_buf_0_rows_c15_empty_n,
        if_read => bgr2gray_9_0_1080_1920_1_U0_p_src_1_read);

    img_buf_0_cols_c16_U : component hls_sobel_axi_stream_top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din,
        if_full_n => img_buf_0_cols_c16_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write,
        if_dout => img_buf_0_cols_c16_dout,
        if_empty_n => img_buf_0_cols_c16_empty_n,
        if_read => bgr2gray_9_0_1080_1920_1_U0_p_src_2_read);

    img_buf_1_data_U : component hls_sobel_axi_stream_top_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_din,
        if_full_n => img_buf_1_data_full_n,
        if_write => bgr2gray_9_0_1080_1920_1_U0_img_buf_1_473_write,
        if_dout => img_buf_1_data_dout,
        if_empty_n => img_buf_1_data_empty_n,
        if_read => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1_473_read);

    img_buf_1a_data_U : component hls_sobel_axi_stream_top_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_din,
        if_full_n => img_buf_1a_data_full_n,
        if_write => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1a_474_write,
        if_dout => img_buf_1a_data_dout,
        if_empty_n => img_buf_1a_data_empty_n,
        if_read => addWeighted_0_0_1080_1920_1_U0_img_buf_1a_474_read);

    img_buf_1b_data_U : component hls_sobel_axi_stream_top_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_din,
        if_full_n => img_buf_1b_data_full_n,
        if_write => Sobel_0_3_0_0_1080_1920_1_false_U0_img_buf_1b_475_write,
        if_dout => img_buf_1b_data_dout,
        if_empty_n => img_buf_1b_data_empty_n,
        if_read => addWeighted_0_0_1080_1920_1_U0_img_buf_1b_475_read);

    img_buf_2_data_U : component hls_sobel_axi_stream_top_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_din,
        if_full_n => img_buf_2_data_full_n,
        if_write => addWeighted_0_0_1080_1920_1_U0_img_buf_2_476_write,
        if_dout => img_buf_2_data_dout,
        if_empty_n => img_buf_2_data_empty_n,
        if_read => gray2bgr_0_9_1080_1920_1_U0_img_buf_2_476_read);

    img_buf_3_data_U : component hls_sobel_axi_stream_top_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_din,
        if_full_n => img_buf_3_data_full_n,
        if_write => gray2bgr_0_9_1080_1920_1_U0_img_buf_3_477_write,
        if_dout => img_buf_3_data_dout,
        if_empty_n => img_buf_3_data_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_img_buf_3_477_read);

    start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_U : component hls_sobel_axi_stream_top_start_for_Sobel_0_3_0_0_1080_1920_1_false_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_din,
        if_full_n => start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write,
        if_dout => start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_dout,
        if_empty_n => start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_empty_n,
        if_read => Sobel_0_3_0_0_1080_1920_1_false_U0_ap_ready);

    start_for_addWeighted_0_0_1080_1920_1_U0_U : component hls_sobel_axi_stream_top_start_for_addWeighted_0_0_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_addWeighted_0_0_1080_1920_1_U0_din,
        if_full_n => start_for_addWeighted_0_0_1080_1920_1_U0_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write,
        if_dout => start_for_addWeighted_0_0_1080_1920_1_U0_dout,
        if_empty_n => start_for_addWeighted_0_0_1080_1920_1_U0_empty_n,
        if_read => addWeighted_0_0_1080_1920_1_U0_ap_ready);

    start_for_gray2bgr_0_9_1080_1920_1_U0_U : component hls_sobel_axi_stream_top_start_for_gray2bgr_0_9_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_gray2bgr_0_9_1080_1920_1_U0_din,
        if_full_n => start_for_gray2bgr_0_9_1080_1920_1_U0_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write,
        if_dout => start_for_gray2bgr_0_9_1080_1920_1_U0_dout,
        if_empty_n => start_for_gray2bgr_0_9_1080_1920_1_U0_empty_n,
        if_read => gray2bgr_0_9_1080_1920_1_U0_ap_ready);

    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_U : component hls_sobel_axi_stream_top_start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din,
        if_full_n => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n,
        if_write => Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write,
        if_dout => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout,
        if_empty_n => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready);

    start_for_bgr2gray_9_0_1080_1920_1_U0_U : component hls_sobel_axi_stream_top_start_for_bgr2gray_9_0_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_bgr2gray_9_0_1080_1920_1_U0_din,
        if_full_n => start_for_bgr2gray_9_0_1080_1920_1_U0_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write,
        if_dout => start_for_bgr2gray_9_0_1080_1920_1_U0_dout,
        if_empty_n => start_for_bgr2gray_9_0_1080_1920_1_U0_empty_n,
        if_read => bgr2gray_9_0_1080_1920_1_U0_ap_ready);





    ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready <= ap_sync_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_0 = AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready) and (ap_sync_ready = ap_const_logic_1))) then 
                AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count <= std_logic_vector(unsigned(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready))) then 
                AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count <= std_logic_vector(unsigned(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_0 = Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready) and (ap_sync_ready = ap_const_logic_1))) then 
                Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready))) then 
                Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start <= ((ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue <= ap_const_logic_1;
    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start <= ((ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n <= (start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n and start_for_gray2bgr_0_9_1080_1920_1_U0_full_n and start_for_addWeighted_0_0_1080_1920_1_U0_full_n and start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_full_n);
    Sobel_0_3_0_0_1080_1920_1_false_U0_ap_continue <= ap_const_logic_1;
    Sobel_0_3_0_0_1080_1920_1_false_U0_ap_start <= start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_empty_n;
    Sobel_0_3_0_0_1080_1920_1_false_U0_start_full_n <= ap_const_logic_1;
    Sobel_0_3_0_0_1080_1920_1_false_U0_start_write <= ap_const_logic_0;
    addWeighted_0_0_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    addWeighted_0_0_1080_1920_1_U0_ap_start <= start_for_addWeighted_0_0_1080_1920_1_U0_empty_n;
    addWeighted_0_0_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    addWeighted_0_0_1080_1920_1_U0_start_write <= ap_const_logic_0;
    ap_done <= xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done;
    ap_idle <= (xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle and gray2bgr_0_9_1080_1920_1_U0_ap_idle and bgr2gray_9_0_1080_1920_1_U0_ap_idle and addWeighted_0_0_1080_1920_1_U0_ap_idle and Sobel_0_3_0_0_1080_1920_1_false_U0_ap_idle and Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle and AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready <= (ap_sync_reg_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready or AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready);
    ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= (ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready or Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready);
    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done;
    ap_sync_ready <= (ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready and ap_sync_AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready);
    bgr2gray_9_0_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    bgr2gray_9_0_1080_1920_1_U0_ap_start <= start_for_bgr2gray_9_0_1080_1920_1_U0_empty_n;
    bgr2gray_9_0_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    bgr2gray_9_0_1080_1920_1_U0_start_write <= ap_const_logic_0;
    gray2bgr_0_9_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    gray2bgr_0_9_1080_1920_1_U0_ap_start <= start_for_gray2bgr_0_9_1080_1920_1_U0_empty_n;
    gray2bgr_0_9_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    gray2bgr_0_9_1080_1920_1_U0_start_write <= ap_const_logic_0;
    p_dst_TDATA <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDATA;
    p_dst_TDEST <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TDEST;
    p_dst_TID <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TID;
    p_dst_TKEEP <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TKEEP;
    p_dst_TLAST <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TLAST;
    p_dst_TSTRB <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TSTRB;
    p_dst_TUSER <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TUSER;
    p_dst_TVALID <= xfMat2AXIvideo_24_9_1080_1920_1_U0_p_dst_TVALID;
    p_src_TREADY <= AXIvideo2xfMat_24_9_1080_1920_1_U0_p_src_TREADY;
    start_for_Sobel_0_3_0_0_1080_1920_1_false_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_addWeighted_0_0_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_bgr2gray_9_0_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_gray2bgr_0_9_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start <= start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write <= ap_const_logic_0;
end behav;
