// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_axi_stream_top_Sobel_0_3_0_0_1080_1920_1_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_buf_1_473_dout,
        img_buf_1_473_empty_n,
        img_buf_1_473_read,
        img_buf_1a_474_din,
        img_buf_1a_474_full_n,
        img_buf_1a_474_write,
        img_buf_1b_475_din,
        img_buf_1b_475_full_n,
        img_buf_1b_475_write,
        p_src_mat_1_dout,
        p_src_mat_1_empty_n,
        p_src_mat_1_read,
        p_src_mat_2_dout,
        p_src_mat_2_empty_n,
        p_src_mat_2_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] img_buf_1_473_dout;
input   img_buf_1_473_empty_n;
output   img_buf_1_473_read;
output  [7:0] img_buf_1a_474_din;
input   img_buf_1a_474_full_n;
output   img_buf_1a_474_write;
output  [7:0] img_buf_1b_475_din;
input   img_buf_1b_475_full_n;
output   img_buf_1b_475_write;
input  [31:0] p_src_mat_1_dout;
input   p_src_mat_1_empty_n;
output   p_src_mat_1_read;
input  [31:0] p_src_mat_2_dout;
input   p_src_mat_2_empty_n;
output   p_src_mat_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_buf_1_473_read;
reg img_buf_1a_474_write;
reg img_buf_1b_475_write;
reg p_src_mat_1_read;
reg p_src_mat_2_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_mat_1_blk_n;
reg    p_src_mat_2_blk_n;
wire   [15:0] width_fu_56_p1;
reg   [15:0] width_reg_66;
reg    ap_block_state1;
wire   [15:0] height_fu_61_p1;
reg   [15:0] height_reg_71;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_idle;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_ready;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1_473_read;
wire   [7:0] grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_din;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_write;
wire   [7:0] grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_din;
wire    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_write;
reg    grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg;
reg    ap_block_state1_ignore_call12;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg = 1'b0;
end

hls_sobel_axi_stream_top_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start),
    .ap_done(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_ready),
    .img_buf_1_473_dout(img_buf_1_473_dout),
    .img_buf_1_473_empty_n(img_buf_1_473_empty_n),
    .img_buf_1_473_read(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1_473_read),
    .img_buf_1a_474_din(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_din),
    .img_buf_1a_474_full_n(img_buf_1a_474_full_n),
    .img_buf_1a_474_write(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_write),
    .img_buf_1b_475_din(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_din),
    .img_buf_1b_475_full_n(img_buf_1b_475_full_n),
    .img_buf_1b_475_write(grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_write),
    .img_height(height_reg_71),
    .img_width(width_reg_66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_reg_71 <= height_fu_61_p1;
        width_reg_66 <= width_fu_56_p1;
    end
end

always @ (*) begin
    if (((grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1_473_read = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1_473_read;
    end else begin
        img_buf_1_473_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1a_474_write = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_write;
    end else begin
        img_buf_1a_474_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_buf_1b_475_write = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_write;
    end else begin
        img_buf_1b_475_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_1_blk_n = p_src_mat_1_empty_n;
    end else begin
        p_src_mat_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_1_read = 1'b1;
    end else begin
        p_src_mat_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_2_blk_n = p_src_mat_2_empty_n;
    end else begin
        p_src_mat_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_2_read = 1'b1;
    end else begin
        p_src_mat_2_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call12 = ((ap_start == 1'b0) | (p_src_mat_2_empty_n == 1'b0) | (p_src_mat_1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_ap_start_reg;

assign height_fu_61_p1 = p_src_mat_1_dout[15:0];

assign img_buf_1a_474_din = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1a_474_din;

assign img_buf_1b_475_din = grp_xFSobelFilter3x3_0_0_1080_1920_1_0_0_1_1_1_1920_false_s_fu_44_img_buf_1b_475_din;

assign width_fu_56_p1 = p_src_mat_2_dout[15:0];

endmodule //hls_sobel_axi_stream_top_Sobel_0_3_0_0_1080_1920_1_false_s
