// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_sobel_axi_stream_top_bgr2gray_9_0_1080_1920_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_buf_0_472_dout,
        img_buf_0_472_empty_n,
        img_buf_0_472_read,
        img_buf_1_473_din,
        img_buf_1_473_full_n,
        img_buf_1_473_write,
        p_src_1_dout,
        p_src_1_empty_n,
        p_src_1_read,
        p_src_2_dout,
        p_src_2_empty_n,
        p_src_2_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state10 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_buf_0_472_dout;
input   img_buf_0_472_empty_n;
output   img_buf_0_472_read;
output  [7:0] img_buf_1_473_din;
input   img_buf_1_473_full_n;
output   img_buf_1_473_write;
input  [31:0] p_src_1_dout;
input   p_src_1_empty_n;
output   p_src_1_read;
input  [31:0] p_src_2_dout;
input   p_src_2_empty_n;
output   p_src_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_buf_0_472_read;
reg img_buf_1_473_write;
reg p_src_1_read;
reg p_src_2_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_buf_0_472_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln4722_reg_247;
reg    img_buf_1_473_blk_n;
reg    ap_enable_reg_pp0_iter6;
reg   [0:0] icmp_ln4722_reg_247_pp0_iter5_reg;
reg    p_src_1_blk_n;
reg    p_src_2_blk_n;
reg   [15:0] empty_60_reg_112;
wire   [15:0] height_fu_123_p1;
reg   [15:0] height_reg_228;
reg    ap_block_state1;
wire   [15:0] width_fu_127_p1;
reg   [15:0] width_reg_233;
wire   [0:0] icmp_ln882_fu_135_p2;
wire    ap_CS_fsm_state2;
wire   [12:0] add_ln695_fu_140_p2;
reg   [12:0] add_ln695_reg_242;
wire   [0:0] icmp_ln4722_fu_146_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_state9_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln4722_reg_247_pp0_iter1_reg;
reg   [0:0] icmp_ln4722_reg_247_pp0_iter2_reg;
reg   [0:0] icmp_ln4722_reg_247_pp0_iter3_reg;
reg   [0:0] icmp_ln4722_reg_247_pp0_iter4_reg;
wire   [15:0] add_ln882_fu_151_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [7:0] p_fu_157_p1;
reg   [7:0] p_reg_256;
reg   [7:0] p_1_reg_261;
reg   [7:0] p_1_reg_261_pp0_iter2_reg;
wire   [21:0] grp_fu_204_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg   [12:0] empty_reg_101;
wire    ap_CS_fsm_state10;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] zext_ln882_fu_131_p1;
wire   [7:0] p_2_fu_171_p4;
wire   [21:0] grp_fu_210_p3;
wire   [22:0] grp_fu_219_p3;
wire   [14:0] grp_fu_204_p0;
wire   [7:0] grp_fu_204_p1;
wire   [12:0] grp_fu_210_p0;
wire   [7:0] grp_fu_210_p1;
wire   [15:0] grp_fu_219_p0;
wire   [7:0] grp_fu_219_p1;
wire   [21:0] grp_fu_219_p2;
reg    grp_fu_204_ce;
reg    grp_fu_210_ce;
reg    grp_fu_219_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [21:0] grp_fu_204_p10;
wire   [19:0] grp_fu_210_p10;
wire   [22:0] grp_fu_219_p10;
wire   [22:0] grp_fu_219_p20;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

hls_sobel_axi_stream_top_mul_mul_15ns_8ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 22 ))
mul_mul_15ns_8ns_22_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_204_p0),
    .din1(grp_fu_204_p1),
    .ce(grp_fu_204_ce),
    .dout(grp_fu_204_p2)
);

hls_sobel_axi_stream_top_mac_muladd_13ns_8ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_13ns_8ns_22ns_22_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_210_p0),
    .din1(grp_fu_210_p1),
    .din2(grp_fu_204_p2),
    .ce(grp_fu_210_ce),
    .dout(grp_fu_210_p3)
);

hls_sobel_axi_stream_top_mac_muladd_16ns_8ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_16ns_8ns_22ns_23_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_219_p0),
    .din1(grp_fu_219_p1),
    .din2(grp_fu_219_p2),
    .ce(grp_fu_219_ce),
    .dout(grp_fu_219_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln882_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln882_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((icmp_ln882_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln4722_fu_146_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        empty_60_reg_112 <= add_ln882_fu_151_p2;
    end else if (((icmp_ln882_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_60_reg_112 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_reg_101 <= add_ln695_reg_242;
    end else if ((~((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_101 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln695_reg_242 <= add_ln695_fu_140_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_reg_228 <= height_fu_123_p1;
        width_reg_233 <= width_fu_127_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln4722_reg_247 <= icmp_ln4722_fu_146_p2;
        icmp_ln4722_reg_247_pp0_iter1_reg <= icmp_ln4722_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln4722_reg_247_pp0_iter2_reg <= icmp_ln4722_reg_247_pp0_iter1_reg;
        icmp_ln4722_reg_247_pp0_iter3_reg <= icmp_ln4722_reg_247_pp0_iter2_reg;
        icmp_ln4722_reg_247_pp0_iter4_reg <= icmp_ln4722_reg_247_pp0_iter3_reg;
        icmp_ln4722_reg_247_pp0_iter5_reg <= icmp_ln4722_reg_247_pp0_iter4_reg;
        p_1_reg_261_pp0_iter2_reg <= p_1_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln4722_reg_247 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_1_reg_261 <= {{img_buf_0_472_dout[15:8]}};
        p_reg_256 <= p_fu_157_p1;
    end
end

always @ (*) begin
    if ((icmp_ln4722_fu_146_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln882_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln882_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_204_ce = 1'b1;
    end else begin
        grp_fu_204_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_210_ce = 1'b1;
    end else begin
        grp_fu_210_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_219_ce = 1'b1;
    end else begin
        grp_fu_219_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4722_reg_247 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_0_472_blk_n = img_buf_0_472_empty_n;
    end else begin
        img_buf_0_472_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln4722_reg_247 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buf_0_472_read = 1'b1;
    end else begin
        img_buf_0_472_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_buf_1_473_blk_n = img_buf_1_473_full_n;
    end else begin
        img_buf_1_473_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_buf_1_473_write = 1'b1;
    end else begin
        img_buf_1_473_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_1_blk_n = p_src_1_empty_n;
    end else begin
        p_src_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_1_read = 1'b1;
    end else begin
        p_src_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_2_blk_n = p_src_2_empty_n;
    end else begin
        p_src_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_2_read = 1'b1;
    end else begin
        p_src_2_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln882_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln4722_fu_146_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b0)) | ((icmp_ln4722_fu_146_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln695_fu_140_p2 = (empty_reg_101 + 13'd1);

assign add_ln882_fu_151_p2 = (empty_60_reg_112 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (img_buf_1_473_full_n == 1'b0)) | ((icmp_ln4722_reg_247 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_buf_0_472_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (img_buf_1_473_full_n == 1'b0)) | ((icmp_ln4722_reg_247 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_buf_0_472_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (img_buf_1_473_full_n == 1'b0)) | ((icmp_ln4722_reg_247 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_buf_0_472_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_src_2_empty_n == 1'b0) | (p_src_1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((icmp_ln4722_reg_247 == 1'd0) & (img_buf_0_472_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter6 = ((icmp_ln4722_reg_247_pp0_iter5_reg == 1'd0) & (img_buf_1_473_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_fu_204_p0 = 22'd9798;

assign grp_fu_204_p1 = grp_fu_204_p10;

assign grp_fu_204_p10 = p_2_fu_171_p4;

assign grp_fu_210_p0 = 20'd3736;

assign grp_fu_210_p1 = grp_fu_210_p10;

assign grp_fu_210_p10 = p_reg_256;

assign grp_fu_219_p0 = 23'd19235;

assign grp_fu_219_p1 = grp_fu_219_p10;

assign grp_fu_219_p10 = p_1_reg_261_pp0_iter2_reg;

assign grp_fu_219_p2 = grp_fu_219_p20;

assign grp_fu_219_p20 = grp_fu_210_p3;

assign height_fu_123_p1 = p_src_1_dout[15:0];

assign icmp_ln4722_fu_146_p2 = ((empty_60_reg_112 == width_reg_233) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_135_p2 = ((zext_ln882_fu_131_p1 < height_reg_228) ? 1'b1 : 1'b0);

assign img_buf_1_473_din = {{grp_fu_219_p3[22:15]}};

assign p_2_fu_171_p4 = {{img_buf_0_472_dout[23:16]}};

assign p_fu_157_p1 = img_buf_0_472_dout[7:0];

assign width_fu_127_p1 = p_src_2_dout[15:0];

assign zext_ln882_fu_131_p1 = empty_reg_101;

endmodule //hls_sobel_axi_stream_top_bgr2gray_9_0_1080_1920_1_s
